[features]
seeds = true
skip-lint = false

[toolchain]
anchor_version = "0.31.0"

[programs.localnet]
aegis_protocol = "AerttabNDRDQkaHZBKka1JFGytct6Bx5hV5Jonrvwryu"

[programs.devnet]
aegis_protocol = "AerttabNDRDQkaHZBKka1JFGytct6Bx5hV5Jonrvwryu"

[programs.mainnet]
aegis_protocol = "Aegis111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"