[features]
seeds = true
skip-lint = false

[programs.localnet]
aegis_protocol = "Aegis111111111111111111111111111111111111111"

[programs.devnet]
aegis_protocol = "41FsEq3HW76tijmW1GxLon4dP8x2Q8m7g9JQ6Y2BFpF1"

[programs.mainnet]
aegis_protocol = "Aegis111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "wallets/aegis-deploy-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"